In [218]:
import numpy as np

In [219]:
# Rewards matrix.
R = np.matrix([
    [-1,-1,-1,-1,0,-1],
    [-1,-1,-1,0,-1,100],
    [-1,-1,-1,0,-1,-1],
    [-1,0,0,-1,0,-1],
    [-1,0,0,-1,-1,100],
    [-1,0,-1,-1,0,100]
])

In [220]:
print(R)

[[ -1  -1  -1  -1   0  -1]
 [ -1  -1  -1   0  -1 100]
 [ -1  -1  -1   0  -1  -1]
 [ -1   0   0  -1   0  -1]
 [ -1   0   0  -1  -1 100]
 [ -1   0  -1  -1   0 100]]


In [221]:
# Initialize the Q- Matrix.
Q = np.matrix(np.zeros([6,6]))

In [222]:
print(Q)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [223]:
# Initialize the learning rate.
gamma = 0.8

In [224]:
# Initial state.
initial_state = 3

In [225]:
# Function to return all the avaiable action in given state.
def avaiable_actions(state):
    current_state_row = R[state]
    av_act = np.where(current_state_row >= 0)[1]
    return av_act

In [226]:
# Function which randomly choose an state from available one.
def sample_next_action(available_action):
    next_action = int(np.random.choice(available_action,1))
    return next_action

In [227]:
def update(current_state,action,gamma):
    max_index = np.where(Q[action]==np.max(Q[action]))[1]
    if max_index.shape[0] > 1:
        max_index = int(np.random.choice(max_index,1))
    else:
        max_index = int(max_index)
    
    max_value = Q[action,max_index]

    # Apply the Q-Learning Formulla.
    Q[current_state,action] = R[current_state,action] + gamma * max_value

In [228]:
# Train for 10000 times.
for i in range(10000):
    current_state = np.random.randint(0,int(Q.shape[0]))
    available_act = avaiable_actions(current_state)
    action = sample_next_action(available_act)
    update(current_state,action,gamma)

In [230]:
# After updation now the Q table look like this.
print(Q)

[[  0.   0.   0.   0. 400.   0.]
 [  0.   0.   0. 320.   0. 500.]
 [  0.   0.   0. 320.   0.   0.]
 [  0. 400. 256.   0. 400.   0.]
 [  0. 400. 256.   0.   0. 500.]
 [  0. 400.   0.   0. 400. 500.]]


In [231]:
# Find a path.
current_state = 2
goal_state = 5
steps = [current_state]

In [238]:
while  current_state != goal_state:
    next_step_index = np.where(Q[current_state]==np.max(Q[current_state]))[1]
    if next_step_index.shape[0] > 1:
        next_step_index = int(np.random.choice(next_step_index,1))
    else:
        next_step_index = int(next_step_index)
    steps.append(next_step_index)
    current_state = next_step_index

print("Path :",steps)

Path : [2, 3, 1, 5]


In [240]:
! jupyter nbextensions_configurator disable

usage: jupyter [-h] [--version] [--config-dir] [--data-dir] [--runtime-dir]
               [--paths] [--json] [--debug]
               [subcommand]

Jupyter: Interactive Computing

positional arguments:
  subcommand     the subcommand to launch

options:
  -h, --help     show this help message and exit
  --version      show the versions of core jupyter packages and exit
  --config-dir   show Jupyter config dir
  --data-dir     show Jupyter data dir
  --runtime-dir  show Jupyter runtime dir
  --paths        show all Jupyter paths. Add --json for machine-readable
                 format.
  --json         output paths as machine-readable json
  --debug        output debug information about paths

Available subcommands: bundlerextension console dejavu events execute fileid
kernel kernelspec lab labextension labhub migrate nbclassic nbconvert
nbextension notebook qtconsole run script server serverextension troubleshoot
trust

Jupyter command `jupyter-nbextensions_configurator` not found.
